/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedReviewIndexRouteImport } from './routes/_authenticated/review.index'
import { Route as AuthenticatedLogIndexRouteImport } from './routes/_authenticated/log.index'
import { Route as AuthenticatedHistoryIndexRouteImport } from './routes/_authenticated/history.index'
import { Route as AuthenticatedGoalsIndexRouteImport } from './routes/_authenticated/goals.index'
import { Route as AuthenticatedReviewMonthRouteImport } from './routes/_authenticated/review.month'
import { Route as AuthenticatedLogWalkingRouteImport } from './routes/_authenticated/log.walking'
import { Route as AuthenticatedLogSuccessRouteImport } from './routes/_authenticated/log.success'
import { Route as AuthenticatedLogStrengthRouteImport } from './routes/_authenticated/log.strength'
import { Route as AuthenticatedLogRunningRouteImport } from './routes/_authenticated/log.running'
import { Route as AuthenticatedLogQuickRouteImport } from './routes/_authenticated/log.quick'
import { Route as AuthenticatedLogCyclingRouteImport } from './routes/_authenticated/log.cycling'
import { Route as AuthenticatedLogCircuitRouteImport } from './routes/_authenticated/log.circuit'
import { Route as AuthenticatedHistoryIdRouteImport } from './routes/_authenticated/history.$id'
import { Route as AuthenticatedGoalsNewRouteImport } from './routes/_authenticated/goals.new'
import { Route as AuthenticatedGoalsIdRouteImport } from './routes/_authenticated/goals.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReviewIndexRoute =
  AuthenticatedReviewIndexRouteImport.update({
    id: '/review/',
    path: '/review/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogIndexRoute = AuthenticatedLogIndexRouteImport.update({
  id: '/log/',
  path: '/log/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryIndexRoute =
  AuthenticatedHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoalsIndexRoute = AuthenticatedGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewMonthRoute =
  AuthenticatedReviewMonthRouteImport.update({
    id: '/review/month',
    path: '/review/month',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogWalkingRoute = AuthenticatedLogWalkingRouteImport.update({
  id: '/log/walking',
  path: '/log/walking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogSuccessRoute = AuthenticatedLogSuccessRouteImport.update({
  id: '/log/success',
  path: '/log/success',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogStrengthRoute =
  AuthenticatedLogStrengthRouteImport.update({
    id: '/log/strength',
    path: '/log/strength',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogRunningRoute = AuthenticatedLogRunningRouteImport.update({
  id: '/log/running',
  path: '/log/running',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogQuickRoute = AuthenticatedLogQuickRouteImport.update({
  id: '/log/quick',
  path: '/log/quick',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogCyclingRoute = AuthenticatedLogCyclingRouteImport.update({
  id: '/log/cycling',
  path: '/log/cycling',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogCircuitRoute = AuthenticatedLogCircuitRouteImport.update({
  id: '/log/circuit',
  path: '/log/circuit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryIdRoute = AuthenticatedHistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsNewRoute = AuthenticatedGoalsNewRouteImport.update({
  id: '/goals/new',
  path: '/goals/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsIdRoute = AuthenticatedGoalsIdRouteImport.update({
  id: '/goals/$id',
  path: '/goals/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/goals/$id': typeof AuthenticatedGoalsIdRoute
  '/goals/new': typeof AuthenticatedGoalsNewRoute
  '/history/$id': typeof AuthenticatedHistoryIdRoute
  '/log/circuit': typeof AuthenticatedLogCircuitRoute
  '/log/cycling': typeof AuthenticatedLogCyclingRoute
  '/log/quick': typeof AuthenticatedLogQuickRoute
  '/log/running': typeof AuthenticatedLogRunningRoute
  '/log/strength': typeof AuthenticatedLogStrengthRoute
  '/log/success': typeof AuthenticatedLogSuccessRoute
  '/log/walking': typeof AuthenticatedLogWalkingRoute
  '/review/month': typeof AuthenticatedReviewMonthRoute
  '/goals/': typeof AuthenticatedGoalsIndexRoute
  '/history/': typeof AuthenticatedHistoryIndexRoute
  '/log/': typeof AuthenticatedLogIndexRoute
  '/review/': typeof AuthenticatedReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/goals/$id': typeof AuthenticatedGoalsIdRoute
  '/goals/new': typeof AuthenticatedGoalsNewRoute
  '/history/$id': typeof AuthenticatedHistoryIdRoute
  '/log/circuit': typeof AuthenticatedLogCircuitRoute
  '/log/cycling': typeof AuthenticatedLogCyclingRoute
  '/log/quick': typeof AuthenticatedLogQuickRoute
  '/log/running': typeof AuthenticatedLogRunningRoute
  '/log/strength': typeof AuthenticatedLogStrengthRoute
  '/log/success': typeof AuthenticatedLogSuccessRoute
  '/log/walking': typeof AuthenticatedLogWalkingRoute
  '/review/month': typeof AuthenticatedReviewMonthRoute
  '/goals': typeof AuthenticatedGoalsIndexRoute
  '/history': typeof AuthenticatedHistoryIndexRoute
  '/log': typeof AuthenticatedLogIndexRoute
  '/review': typeof AuthenticatedReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/goals/$id': typeof AuthenticatedGoalsIdRoute
  '/_authenticated/goals/new': typeof AuthenticatedGoalsNewRoute
  '/_authenticated/history/$id': typeof AuthenticatedHistoryIdRoute
  '/_authenticated/log/circuit': typeof AuthenticatedLogCircuitRoute
  '/_authenticated/log/cycling': typeof AuthenticatedLogCyclingRoute
  '/_authenticated/log/quick': typeof AuthenticatedLogQuickRoute
  '/_authenticated/log/running': typeof AuthenticatedLogRunningRoute
  '/_authenticated/log/strength': typeof AuthenticatedLogStrengthRoute
  '/_authenticated/log/success': typeof AuthenticatedLogSuccessRoute
  '/_authenticated/log/walking': typeof AuthenticatedLogWalkingRoute
  '/_authenticated/review/month': typeof AuthenticatedReviewMonthRoute
  '/_authenticated/goals/': typeof AuthenticatedGoalsIndexRoute
  '/_authenticated/history/': typeof AuthenticatedHistoryIndexRoute
  '/_authenticated/log/': typeof AuthenticatedLogIndexRoute
  '/_authenticated/review/': typeof AuthenticatedReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/achievements'
    | '/dashboard'
    | '/settings'
    | '/goals/$id'
    | '/goals/new'
    | '/history/$id'
    | '/log/circuit'
    | '/log/cycling'
    | '/log/quick'
    | '/log/running'
    | '/log/strength'
    | '/log/success'
    | '/log/walking'
    | '/review/month'
    | '/goals/'
    | '/history/'
    | '/log/'
    | '/review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/achievements'
    | '/dashboard'
    | '/settings'
    | '/goals/$id'
    | '/goals/new'
    | '/history/$id'
    | '/log/circuit'
    | '/log/cycling'
    | '/log/quick'
    | '/log/running'
    | '/log/strength'
    | '/log/success'
    | '/log/walking'
    | '/review/month'
    | '/goals'
    | '/history'
    | '/log'
    | '/review'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/achievements'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/goals/$id'
    | '/_authenticated/goals/new'
    | '/_authenticated/history/$id'
    | '/_authenticated/log/circuit'
    | '/_authenticated/log/cycling'
    | '/_authenticated/log/quick'
    | '/_authenticated/log/running'
    | '/_authenticated/log/strength'
    | '/_authenticated/log/success'
    | '/_authenticated/log/walking'
    | '/_authenticated/review/month'
    | '/_authenticated/goals/'
    | '/_authenticated/history/'
    | '/_authenticated/log/'
    | '/_authenticated/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review/': {
      id: '/_authenticated/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof AuthenticatedReviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log/': {
      id: '/_authenticated/log/'
      path: '/log'
      fullPath: '/log/'
      preLoaderRoute: typeof AuthenticatedLogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history/': {
      id: '/_authenticated/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthenticatedHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals/': {
      id: '/_authenticated/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof AuthenticatedGoalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review/month': {
      id: '/_authenticated/review/month'
      path: '/review/month'
      fullPath: '/review/month'
      preLoaderRoute: typeof AuthenticatedReviewMonthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log/walking': {
      id: '/_authenticated/log/walking'
      path: '/log/walking'
      fullPath: '/log/walking'
      preLoaderRoute: typeof AuthenticatedLogWalkingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log/success': {
      id: '/_authenticated/log/success'
      path: '/log/success'
      fullPath: '/log/success'
      preLoaderRoute: typeof AuthenticatedLogSuccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log/strength': {
      id: '/_authenticated/log/strength'
      path: '/log/strength'
      fullPath: '/log/strength'
      preLoaderRoute: typeof AuthenticatedLogStrengthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log/running': {
      id: '/_authenticated/log/running'
      path: '/log/running'
      fullPath: '/log/running'
      preLoaderRoute: typeof AuthenticatedLogRunningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log/quick': {
      id: '/_authenticated/log/quick'
      path: '/log/quick'
      fullPath: '/log/quick'
      preLoaderRoute: typeof AuthenticatedLogQuickRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log/cycling': {
      id: '/_authenticated/log/cycling'
      path: '/log/cycling'
      fullPath: '/log/cycling'
      preLoaderRoute: typeof AuthenticatedLogCyclingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log/circuit': {
      id: '/_authenticated/log/circuit'
      path: '/log/circuit'
      fullPath: '/log/circuit'
      preLoaderRoute: typeof AuthenticatedLogCircuitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history/$id': {
      id: '/_authenticated/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof AuthenticatedHistoryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals/new': {
      id: '/_authenticated/goals/new'
      path: '/goals/new'
      fullPath: '/goals/new'
      preLoaderRoute: typeof AuthenticatedGoalsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals/$id': {
      id: '/_authenticated/goals/$id'
      path: '/goals/$id'
      fullPath: '/goals/$id'
      preLoaderRoute: typeof AuthenticatedGoalsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedGoalsIdRoute: typeof AuthenticatedGoalsIdRoute
  AuthenticatedGoalsNewRoute: typeof AuthenticatedGoalsNewRoute
  AuthenticatedHistoryIdRoute: typeof AuthenticatedHistoryIdRoute
  AuthenticatedLogCircuitRoute: typeof AuthenticatedLogCircuitRoute
  AuthenticatedLogCyclingRoute: typeof AuthenticatedLogCyclingRoute
  AuthenticatedLogQuickRoute: typeof AuthenticatedLogQuickRoute
  AuthenticatedLogRunningRoute: typeof AuthenticatedLogRunningRoute
  AuthenticatedLogStrengthRoute: typeof AuthenticatedLogStrengthRoute
  AuthenticatedLogSuccessRoute: typeof AuthenticatedLogSuccessRoute
  AuthenticatedLogWalkingRoute: typeof AuthenticatedLogWalkingRoute
  AuthenticatedReviewMonthRoute: typeof AuthenticatedReviewMonthRoute
  AuthenticatedGoalsIndexRoute: typeof AuthenticatedGoalsIndexRoute
  AuthenticatedHistoryIndexRoute: typeof AuthenticatedHistoryIndexRoute
  AuthenticatedLogIndexRoute: typeof AuthenticatedLogIndexRoute
  AuthenticatedReviewIndexRoute: typeof AuthenticatedReviewIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedGoalsIdRoute: AuthenticatedGoalsIdRoute,
  AuthenticatedGoalsNewRoute: AuthenticatedGoalsNewRoute,
  AuthenticatedHistoryIdRoute: AuthenticatedHistoryIdRoute,
  AuthenticatedLogCircuitRoute: AuthenticatedLogCircuitRoute,
  AuthenticatedLogCyclingRoute: AuthenticatedLogCyclingRoute,
  AuthenticatedLogQuickRoute: AuthenticatedLogQuickRoute,
  AuthenticatedLogRunningRoute: AuthenticatedLogRunningRoute,
  AuthenticatedLogStrengthRoute: AuthenticatedLogStrengthRoute,
  AuthenticatedLogSuccessRoute: AuthenticatedLogSuccessRoute,
  AuthenticatedLogWalkingRoute: AuthenticatedLogWalkingRoute,
  AuthenticatedReviewMonthRoute: AuthenticatedReviewMonthRoute,
  AuthenticatedGoalsIndexRoute: AuthenticatedGoalsIndexRoute,
  AuthenticatedHistoryIndexRoute: AuthenticatedHistoryIndexRoute,
  AuthenticatedLogIndexRoute: AuthenticatedLogIndexRoute,
  AuthenticatedReviewIndexRoute: AuthenticatedReviewIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
